apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webapp-dotnet
  description: "Provision webapp & deploy dotnet app"
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    github.com/project-slug: ${{ parameters.repoUrl }}}
    github-actions: enabled
spec:
  type: service
  owner: prayankag
  lifecycle: production
